### ISSUE TITLE
Repository issue

### ISSUE THREAD

**Issue by amin-amini** [musichin/ReactiveLiveData#5]
Hello,
First of all I should appreciate your great library.
There is an abnormal issue I am facing with your repository. I cannot sync my project when using
```
repositories {
    maven { url 'https://dl.bintray.com/musichin/maven' }
}

dependencies {
    implementation 'com.github.musichin.reactivelivedata:reactivelivedata:0.23.0'
    //or
    implementation 'com.github.musichin.reactivelivedata:reactivelivedata:0.24.0'
}
```

My error is simply `Read Time Out`

but using the Jitpack everything is ok and I use this one
`implementation 'com.github.musichin:ReactiveLiveData:0.23.0'`

In fact, this is not an issue, I just want to people know that they can use Jitpack instead

**Comment by musichin** [comment]
Thanks for opening an issue.
Maybe it was an temporally issue?! Everything is working at the moment for me.

**Comment by musichin** [comment]
resolved.
